import { ADMIN_MANAGE_SONGS_STRINGS } from "../../../i18n/ui/admin/manage-songs";
import { ADMIN_MANAGE_USERS_STRINGS } from "../../../i18n/ui/admin/manage-users";

export const songs_headers = [
    ADMIN_MANAGE_SONGS_STRINGS.TABLE.ID,
    ADMIN_MANAGE_SONGS_STRINGS.TABLE.TITLE,
    ADMIN_MANAGE_SONGS_STRINGS.TABLE.ARTIST,
    ADMIN_MANAGE_SONGS_STRINGS.TABLE.GENRE,
    ADMIN_MANAGE_SONGS_STRINGS.TABLE.DURATION,
    ADMIN_MANAGE_SONGS_STRINGS.TABLE.ACTIONS
];

export const users_headers = [
    ADMIN_MANAGE_USERS_STRINGS.TABLE.NAME,
    ADMIN_MANAGE_USERS_STRINGS.TABLE.ROLE,
    ADMIN_MANAGE_USERS_STRINGS.TABLE.ACTIONS
];